### ISSUE TITLE
Latest Raspbian has Kernal panic after running setup. Pi does not reboot.

### ISSUE THREAD

**Issue by solarsootysmudge** [sbcshop/PiTalk_5#1]
Problem: Latest Raspbian has Kernal panic after running setup. Pi does not reboot.

Steps to replicate
Replicated several times using a fresh SD card image of NOOBS. Installed Raspbian. Ran sudo apt-get update & sudo apt-get dist-upgrade
git clone https://github.com/sbcshop/PiTalk_5.git
Go to directory 'PiTalk_5' and run the command to change the permissions:
sudo chmod +x setup
and then run 'setup', but make sure Raspberry Pi is connected to Internet.
sudo ./setup

It will report the new amount of space required as ask for confimation. Enter y.
Files are downloaded without error.

User then asked to if a reboot should take place. Enter y.

Kernal panic - not syncing: VFS: unable to mount root fs on unknown-block(179,2)

**Comment by sbcshop** [comment]
Hi solarsootysmudge,

We will check this issue. Can you give some more details:

1. Are you using Win32Diskimager or DD command for the card?
2. Have you checked with Raspbian only (without NOOBS)?

Regards

**Comment by solarsootysmudge** [comment]
1. Started off with Win32Diskimage to write a good working img of existing NOOBS build. Then tried clean install by dropping brand new NOOBS onto new FAT32 formated SD card.

2. Currently testing without NOOBS. Looking good so far. This time using Etcher to write Rapbian img directly to card.

Running through a few more tests today. To see if problem related to just NOOBS booting. If this is the case I suggest a minor change to install instructions to make sure end users are not using NOOBS booting. I will let you know how things turn out.

**Comment by sbcshop** [comment]
Thanks for your feedback. 
We are also testing it with NOOBS setup and will update soon.

Regards
